### ISSUE TITLE
word prediction (next code prediction or autocomplete) based on programming language

### ISSUE THREAD

**Issue by fireclouu** [gazlaws-dev/codeboard#11]
supports for next word prediction (i.e.  typing "incl" will suggest "include", or "android:te" will completes to "android:text:")

**Comment by theintel** [comment]
That should probably make the keyboard app huge. I think we should expect this feature from another standalone app.

**Comment by ChiefMikeK** [comment]
Re: 

> termux + pkg install vim
please; "Keep it simple" no to app enhancements that = bloating !

**Comment by chagai95** [comment]
maybe we can work on this on a different branch? and just push to that branch, perhaps release a different app, if it really bloats the app?
I would love to work on such a feature.
I would start with java prediction because that is easier for me, later on, we could add other languages and I actually think word prediction should come at the end, because that would require more work, with downloading libraries and so on...

**Comment by gazlaws-dev** [comment]
This would be better done in an editor rather than the keyboard. This is not likely to make it into the main repo, so feel free to make a fork!
