### ISSUE TITLE
Change icon for backspace button

### ISSUE THREAD

**Issue by fireclouu** [gazlaws-dev/codeboard#13]

**Comment by theintel** [comment]
Why? Although its identical with the "left key", I think its cool how it is.

**Comment by igrad** [comment]
I think it really just doesn't fit the theme of the rest of the keyboard. Especially on Dark material theme, it just doesn't fit the color scheme.

**Comment by gazlaws-dev** [comment]
Assigning this issue to @shruti-b150034cs 
This is a good reference about custom android keyboards: http://www.fampennings.nl/maarten/android/09keyboard/index.htm

Under section 3.4.3, you'll find what you need for this bug (`android:keyIcon`)

1. Add a back icon in the `app/src/main/res/drawable` folder.
2. Update the key to show the icon instead of  '◀'

There are too many templates in [app/src/main/res/xml/](https://github.com/gazlaws-dev/codeboard/tree/master/app/src/main/res/xml)for each size/layout/qwert/azerty/portrait/landscape for the keyboard, so changing the icon in each file is time-consuming.

I have a script in `testxml/makeQ1` that helps to generate all of these. 

The back button should be in `testxml/qwertyrows` (row4 or row 5 depending on when I've changed the layout) and `testxml/azertyrows`

` <Key
            android:codes="-5"
            android:keyEdgeFlags="right"
            android:isRepeatable="true"
android:keyLabel="◀" />`

You'll have to remove `android:keyLabel="◀" ` and add this instead `android:keyIcon="@drawable/back_icon_file_name` 

Or if the icon looks weird (see step 6), try something like `android:keyLabel="Back"` or a unicode character from [here](http://graphemica.com) (I used [this](http://graphemica.com/%E2%97%80), but try [this](http://graphemica.com/%F0%9F%94%99))

The problem with unicode characters is that it looks different on different devices, system fonts, etc.

3. Now you've updated `testxml/qwertyrows/row4`. The script `makeQ1` has the project directory hardcoded as `~/AndroidStudioProjects/CodeBoard`, so if you cloned this repo in another folder you'll have to replace all those lines with your path.

eg `sed -f qwerty0Edit.sed KeyboardTemplate7.xml > YOUR_PATH/CodeBoard/app/src/main/res/xml/qwerty2r.xml`

To run the script:
`bash makeQ1`
4. Check an xml file to see if the script actually saved the files, eg `app/src/main/res/xml/qwerty2r.xml`
5. If you don't see the changes, check your `makeQ1` file to see if the directory is right.
6. Run the project in your phone and test a few layouts, how the icon looks in landscape, etc. Your icon file may be too big or small, so the 'real' bug fixing is repeating steps 1-5 and seeing which icon looks best.

**Comment by gazlaws-dev** [comment]
Assigning this to @UltimateGamer07

**Comment by UltimateGamer07** [comment]
Executing the bash isnt changing anything. I checked the makeQ1 file
I have the whole thing on D:/Android/codeboard

so i made the path in makeQ1 as
/d/android/codeboard/app/src/main/res/xml/qwerty0e.xml

instead of
 ~/AndroidStudioProjects/CodeBoard/app/src/main/res/xml/qwerty0e.xml

in each entry in makeQ1. Yet the changes i make in row5 file in testxml/qwertyrows and ro4 file in testxml/azetyrows isnt reflecting in those files

**Comment by UltimateGamer07** [comment]
I made a new icon using XML , tested it out and pushed it to my repo. Im not sure how to push it to this main repo.

Its much better than the previous design but needs to be refined a little bit more

**Comment by UltimateGamer07** [comment]
> 6. Run the project in your phone and test a few layouts, how the icon looks in landscape, etc. Your icon file may be too big or small, so the real work is repeating steps 1-5 and seeing which icon looks best.

I did that and everything seems fine. However when i tried the light theme, since the button is white colored , it doesnt show up. I saw that the other keys turn black when using the light theme, Is this color change part of the maincode? Or must i create a seperate XML file with dark and use it somewhere?

**Comment by danielo515** [comment]
I also find the icon a bit annoying, so thumbs up for this
